Lecture 2 - PLP, demodata, PDP
alexeyburak/phoneshop-servlet-api pull request #2
Opened 2023-05-06 19:18 UTC by alexeyburak

During this pool request were implemented:

- PLP search form;
- PLP sorting;
- Product demodata servlet context listener;
- PDP;
- Product price history.

2023-05-09 15:23 UTC, alexeyburak commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                .build() : null;
maybe it is better to use Optional here? smth like

```java 
 return Optional.ofNullable(sortField)
            .map(field -> ProductSortCriteriaDTO.builder()
                    .sortField(SortField.valueOf(field))
                    .sortOrder(SortOrder.valueOf(sortOrder))
                    .build()
);
```

end than in next layers write 

```java
Optional.isPresent()
```

2023-05-10 00:39 UTC, marharyta-aheyanka requested changes

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/comparator/ProductKeywordMatchesComparator.java
> +                .count();
you could move this logic to separate method to avoid the duplication:
(int) Arrays.stream(keywords)
                .filter(keyword -> isContainsIgnoreCase(p.getDescription(), keyword))
                .count();

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/dao/implementation/ProductDaoImpl.java
> +				.sorted(new ProductKeywordMatchesComparator(keywords))
It is better to filter first and then sort products, not vice versa

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/dao/implementation/ProductDaoImpl.java
> +		return executeReadLock(() -> productList);
Why do you apply readLock only at the end of the method?

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/dto/ProductSortCriteriaDTO.java
> +public class ProductSortCriteriaDTO {
I'm concerned about "DTO" postfix because in general we don't pass dto's to model layer
Better rename to ProductSortCriteria

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                .orElse("");
use StringUtils.EMPTY instead of ""

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +                .sortField(SortField.valueOf(sortField))
What happens if sortOrder is null?

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/dao/implementation/ProductDaoImpl.java
> +        this.products = products;
public constructor contradicts singleton pattern concept

2023-05-10 00:39 UTC, marharyta-aheyanka commented on src/main/webapp/WEB-INF/web.xml
> +    <error-code>500</error-code>
what about 404 error?

2023-05-11 20:59 UTC, marharyta-aheyanka requested changes

2023-05-11 20:59 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/comparator/ProductKeywordMatchesComparator.java
> +                .filter(keyword -> isContainsIgnoreCase((product.getDescription()), keyword))
Better rename to "containsIgnoreCase"

2023-05-11 21:15 UTC, merged