Lecture 4 - cart CRUD operations, minicart
alexeyburak/phoneshop-servlet-api pull request #4
Opened 2023-05-21 13:59 UTC by alexeyburak

During this pull request were implemented:

- Showing cart in a separate page;
- Updating cart items;
- Deleting cart items;
- Mini cart on header;
- PLP add to cart.

Fixed errors:

- Adding item with 0 amount;
- Adding item with negative amount;
- Adding a fractional quantity.

2023-05-21 14:03 UTC, alexeyburak commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +    private boolean isProductAddedToCart(HttpServletRequest request, HttpServletResponse response, UUID id)
i know about code duplication from PDP servlet here
want to discuss where it is better to move these methods

2023-05-22 23:37 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/CartPageServlet.java
> +                        int quantity = parseQuantity(quantityString, locale);
better move this validation logic to separate method

2023-05-23 00:16 UTC, marharyta-aheyanka requested changes

2023-05-23 00:16 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +            response.sendRedirect(request.getContextPath() + "/products?message=Product added to cart");
what about sorting params, you loose them in this case

2023-05-29 14:53 UTC, merged